<?php

namespace Tests\Unit;

use App\Events\PostCreated;
use App\Jobs\SendEmailToSubscribersJob;
use App\Listeners\SendPostToWebsiteSubscribers;
use App\Mail\SendPost;
use App\Models\User;
use App\Models\Website;
use App\Models\Post;
use App\Models\WebsiteSubscription;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Bus;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Mail;
use Tests\TestCase;

class SendPostToWebsiteSubscribeListenerTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Event::fake();
        Bus::fake();

        Website::factory()->create();
        User::factory()->create(['email'=>'quabenaa@gmail.com']);
        WebsiteSubscription::factory()->create();
    }

    public function testThatListenerIsAttachedToPostCreatedEvent()
    {
        Event::assertListening(
            PostCreated::class,
            SendPostToWebsiteSubscribers::class,
        );
    }

    public function testThatListenerWillDispatchTheEmailJob()
    {
        $post = Post::factory()->create(["title"=>"Send Email", "description"=>"you are going to receive and email"]);
        (new SendPostToWebsiteSubscribers())->handle(new PostCreated($post));
        Bus::assertDispatched(SendEmailToSubscribersJob::class);
    }

}
